version: "3.3"

services:
  web:
    image: madifa-world:latest
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8008:80

  db:
    build:
      context: ./
      dockerfile: Dockerfile.database
    restart: always
    ports:
      - "3307:3306"
